In [1]:
import numpy as np

In [2]:
#Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sonu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sonu/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sonu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sonu/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sonu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sonu/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sonu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sonu/anaconda3\\Libr

In [3]:
#Create a null vector of size 10
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Create a null vector of size 10 but the fifth value which is 1
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
# Create a vector with values ranging from 10 to 49
s = np.arange(10,50)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# Reverse a vector (first element becomes last) 
s[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8
s1=np.arange(9).reshape(3,3)
s1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#Find indices of non-zero elements from [1,2,0,0,4,0] 
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [9]:
#Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#Create a 3x3x3 array with random values
np.random.random((3,3,3))

array([[[0.33926422, 0.62242907, 0.17395027],
        [0.0884108 , 0.95398783, 0.15917521],
        [0.62458978, 0.82888637, 0.98984886]],

       [[0.70956438, 0.02457239, 0.29453832],
        [0.182937  , 0.36161897, 0.67259224],
        [0.28137842, 0.96581399, 0.21045344]],

       [[0.56928512, 0.22293591, 0.68760137],
        [0.49426914, 0.61699396, 0.9351502 ],
        [0.52325375, 0.40079631, 0.5563103 ]]])

In [11]:
#Create a 10x10 array with random values and find the minimum and maximum values
s=np.random.random((10,10))
print(np.max(s))
print(np.min(s))

0.9888789559816324
0.008625723554431919


In [12]:
#Create a random vector of size 30 and find the mean value 
np.random.random(30).mean()

0.43323710584710456

In [13]:
#Create a 2d array with 1 on the border and 0 inside
s=np.ones((10,10))
s[1:-1,1:-1]=0
s

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
#What is the result of the following expression?
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf==np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


In [15]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [16]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
s=np.zeros((8,8))
s[1::2,::2]=1
s[::2,1::2]=1
s

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [17]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [18]:
np.random.random((2,3,2))

array([[[0.74873867, 0.61208405],
        [0.81757109, 0.17852249],
        [0.51736952, 0.60700347]],

       [[0.12881906, 0.43487691],
        [0.05840903, 0.0222857 ],
        [0.4152758 , 0.37240268]]])

In [19]:
print(np.unravel_index(9,(2,3,2)))

(1, 1, 1)


In [20]:
# Create a checkerboard 8x8 matrix using the tile function
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [21]:
# Normalize a 5x5 random matrix
a=np.random.random((5,5))
norm = (a-np.min(a))/(np.max(a)-np.min(a))
norm

array([[0.44186566, 0.24036401, 0.61241304, 0.06078184, 0.91978054],
       [0.43493232, 0.177814  , 0.84821531, 0.54095366, 1.        ],
       [0.87957517, 0.45343576, 0.60952179, 0.39514072, 0.58989476],
       [0.16427051, 0.15981034, 0.22084356, 0.        , 0.87660854],
       [0.77706923, 0.01777612, 0.08820807, 0.75027139, 0.23197803]])

In [22]:
# Create a custom dtype that describes a color as four unisgned bytes (RGBA)
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1),])
color

C:\Users\Sonu\AppData\Local\Temp\ipykernel_11744\160993759.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r",np.ubyte,1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [23]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [24]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
z=np.arange(11)
z[(z>3)&(z<8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [25]:
# What is the output of the following script?
print(sum(range(5),-1))
print(sum(range(5),1))
print(sum(range(5)))

9
11
10


In [26]:
from numpy import *
print(sum(range(5),-1))
print(sum(range(5)))

10
10


In [27]:
#Consider an integer vector Z, which of these expressions are legal?
z=np.arange(10).reshape(2,5)
print(z**z)
print(2 << z >> 2)
print(1j*z)
print(z/1/1)
# print(z<z>z)

[[        1         1         4        27       256]
 [     3125     46656    823543  16777216 387420489]]
[[  0   1   2   4   8]
 [ 16  32  64 128 256]]
[[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
 [0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [28]:
# What are the result of the following expressions?
print(np.array(0)//np.array(0))
print(np.array(0)//np.array(0.))
print(np.array(0)/np.array(0.))
print(np.array(0)/np.array(0))

0
nan
nan
nan


C:\Users\Sonu\AppData\Local\Temp\ipykernel_11744\450048791.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
C:\Users\Sonu\AppData\Local\Temp\ipykernel_11744\450048791.py:3: RuntimeWarning: invalid value encountered in floor_divide
  print(np.array(0)//np.array(0.))
C:\Users\Sonu\AppData\Local\Temp\ipykernel_11744\450048791.py:4: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0.))
C:\Users\Sonu\AppData\Local\Temp\ipykernel_11744\450048791.py:5: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))


In [29]:
# How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print (np.trunc(Z + np.copysign(0.5, Z)))

[-9.  4.  3. -4. -6.  6. -1. -0.  0.  4.]


In [30]:
# . Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 1. 9. 2. 8. 3. 1. 4. 3. 3.]
[1. 1. 9. 2. 8. 3. 1. 4. 3. 3.]
[1. 1. 9. 2. 8. 3. 1. 4. 3. 3.]
[1 1 9 2 8 3 1 4 3 3]
[1. 1. 9. 2. 8. 3. 1. 4. 3. 3.]


In [31]:
# Create a 5x5 matrix with row values ranging from 0 to 4
z = np.zeros((5,5))
z+=np.arange(0,5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [32]:
# Consider a generator function that generates 10 integers and use it to build anarray
def generator():
    for i in range(11):
        yield i
    
z = np.fromiter(generator(),dtype=float,count=-1)
z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
z=np.linspace(0,1,12,endpoint=True)[1:-1]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [34]:
#Create a random vector of size 10 and sort it 
np.sort(np.random.random(10))

array([0.05039182, 0.11054267, 0.18346799, 0.20448364, 0.24055145,
       0.24822495, 0.25441406, 0.44816305, 0.57309158, 0.73591324])

In [35]:
#How to sum a small array faster than np.sum?
z=np.arange(10)
np.add.reduce(z)

45

In [36]:
# Consider two random array A anb B, check if they are equal 
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
np.allclose(a,b)


False

In [37]:
# Make an array immutable (read­only) 
z = np.zeros(10)
z.flags.writeable=False
z[0]=1

ValueError: assignment destination is read-only

In [38]:
# Create random vector of size 10 and replace the maximum value by 0
a = np.random.random(10)
a[a.argmax()]=0
a

array([0.        , 0.84593822, 0.54711495, 0.38919332, 0.77316521,
       0.15105324, 0.35217051, 0.46587252, 0.45239102, 0.29706054])

In [39]:
# How to convert a float (32 bits) array into an integer (32 bits) in place?
z = np.arange(10,dtype=np.float32)
print(z.astype('int32'))

[0 1 2 3 4 5 6 7 8 9]


In [40]:
# How to read the following file?

# # File content:
# # -------------
# 1,2,3,4,5
# 6,,,7,8
# ,,9,10,11
# # --------


a = np.genfromtxt('missin.txt',delimiter=',')
a

array([[nan,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., nan]])

In [41]:
# How to randomly place p elements in a 2D array?
n = 10
p = 3
z=np.zeros((n,n))
np.put(z,np.random.choice(range(n*n),p,replace=False),1)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
# Subtract the mean of each row of a matrix
z = np.random.rand(5,10)
z - z.mean(axis=1,keepdims=True)

array([[ 0.01455104,  0.08440217,  0.12164486, -0.41009211,  0.05788659,
        -0.26307656,  0.32534273, -0.33165629,  0.50879147, -0.10779389],
       [-0.01202215,  0.33214865, -0.01706557, -0.12093208, -0.32184358,
         0.38741781, -0.32242172,  0.36170812,  0.04452179, -0.33151128],
       [-0.34528263,  0.07239446, -0.38446131,  0.24926316,  0.32155117,
        -0.16341247,  0.3020089 , -0.39265019, -0.17344177,  0.51403068],
       [ 0.42272855,  0.05279973,  0.40345255, -0.50120464,  0.02831058,
        -0.126231  , -0.20299338,  0.27878377, -0.38868213,  0.03303598],
       [-0.42065018,  0.39980766,  0.36597112, -0.40368259,  0.49710697,
        -0.14798622, -0.2770575 , -0.09969768, -0.36906708,  0.4552555 ]])

In [43]:
#  How to I sort an array by the nth column? 
z = np.random.randint(0,10,(3,3))
print(z[z[:,1].argsort()])

[[4 2 5]
 [2 5 7]
 [5 7 9]]


In [44]:
#  How to tell if a given 2D array has null columns?
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


In [45]:
# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
z = np.ones((5,5,3))
b = np.ones((5,5))
z*b[:,:,None]

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
# How to swap two rows of an array?
a=np.arange(6).reshape(3,2)
a[[0,1]]=a[[1,0]]
a

array([[2, 3],
       [0, 1],
       [4, 5]])

In [47]:
#Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?
a=np.bincount([1,1,2,3,4,4,6])
c=np.repeat(np.arange(len(a)),a)
print(c)

[1 1 2 3 4 4 6]


In [48]:
#How to find the most frequent value in an array?
z = np.random.randint(0,10,50)
np.bincount(z).argmax()

4